/**
 * Golden Semantic Anchors — ALTRO IP v1.3 (дистилляция смыслов для Forge).
 * Схема совместима с экспортом в distilledAnchors.json и взвешенными центроидами.
 *
 * Веса при сборке: core=1.0, nuances=0.7, isoMarkers=1.0
 */

export const DISTILLED_META = {
  version: '1.3',
  forgeLabel: 'ALTRO-IP-distilled',
  distillationNote:
    'Экспертная калибровка терминов по 13 доменам (RU/EN/DE/FR/IT/ES/HY/Latin + ISO/CI). ' +
    'При наличии локальной Qwen — замените блоки core/nuances расширенным выводом модели, сохранив схему JSON.',
  languages: ['ru', 'en', 'de', 'fr', 'it', 'es', 'hy', 'la'] as const,
};

export const CRITICAL_INJECTION_V13: readonly string[] = [
  'смысл',
  'meaning',
  'իմաստ',
  'imast',
  'намерение',
  'intent',
  'մտադրություն',
  'mtadrutyun',
  'iso9001',
  'iso',
  'iec',
  'ci',
  'cd',
  'finalitas',
  'предумышленность',
];

export type DistilledDomainBlock = {
  core: readonly string[];
  nuances: readonly string[];
  isoMarkers: readonly string[];
};

export const DISTILLED_ANCHORS_PAYLOAD: {
  meta: typeof DISTILLED_META & { criticalInjection: readonly string[] };
  domains: Record<string, DistilledDomainBlock>;
} = {
  meta: {
    ...DISTILLED_META,
    criticalInjection: CRITICAL_INJECTION_V13,
  },
  domains: {
    economics: {
      core: [
        'economy',
        'market',
        'trade',
        'finance',
        'capital',
        'supply',
        'demand',
        'investment',
        'profit',
        'growth',
        'экономика',
        'рынок',
        'финансы',
        'капитал',
        'Wirtschaft',
        'Handel',
        'Finanzen',
        'économie',
        'marché',
        'economia',
        'mercato',
        'economía',
        'mercado',
        'տնտեսություն',
        'pecunia',
        'mercatus',
        'oeconomia',
        'commerce',
        'pricing',
      ],
      nuances: [
        'liquidity',
        'solvency',
        'leverage',
        'marginal',
        'субсидия',
        'ликвидность',
        'рентабельность',
        'externalities',
        'opportunity cost',
        'elasticity',
      ],
      isoMarkers: ['ISO 4217', 'ISO 20022', 'GDP', 'CPI', 'PPP', 'SWIFT'],
    },
    politics: {
      core: [
        'politics',
        'government',
        'state',
        'policy',
        'election',
        'democracy',
        'sovereignty',
        'legitimacy',
        'политика',
        'государство',
        'власть',
        'выборы',
        'Politik',
        'Regierung',
        'Staat',
        'politique',
        'gouvernement',
        'politica',
        'governo',
        'política',
        'gobierno',
        'քաղաքականություն',
        'res publica',
        'civitas',
        'imperium',
        'consensus',
      ],
      nuances: [
        'partisanship',
        'mandate',
        'coalition',
        'vetocracy',
        'geopolitics',
        'legitimation',
        'soft power',
        'hard power',
        'polarize',
        'lobbying',
      ],
      isoMarkers: ['ISO 3166', 'UN SDG', 'NATO', 'OSCE', 'G7', 'G20'],
    },
    society: {
      core: [
        'society',
        'social',
        'community',
        'public',
        'citizen',
        'civil',
        'norm',
        'institution',
        'общество',
        'сообщество',
        'гражданин',
        'Gesellschaft',
        'sozial',
        'Gemeinschaft',
        'société',
        'sociale',
        'sociedad',
        'comunità',
        'comunidad',
        'հասարակություն',
        'societas',
        'communitas',
        'populus',
        'civis',
      ],
      nuances: [
        'solidarity',
        'inclusion',
        'cohesion',
        'anomie',
        'stigma',
        'mobility',
        'demography',
        'urbanization',
        'civil society',
        'social contract',
      ],
      isoMarkers: ['ISO 26000', 'SA8000', 'ESG', 'CSR'],
    },
    history: {
      core: [
        'history',
        'historical',
        'past',
        'tradition',
        'heritage',
        'chronicle',
        'epoch',
        'история',
        'прошлое',
        'наследие',
        'Geschichte',
        'Vergangenheit',
        'histoire',
        'passé',
        'storia',
        'historia',
        'pasado',
        'historia',
        'պատմություն',
        'memoria',
        'chronica',
        'annales',
        'epocha',
      ],
      nuances: [
        'teleology',
        'causality',
        'contingency',
        'revisionism',
        'archival',
        'genealogy',
        'periodization',
        'historiography',
        'counterfactual',
        'zeitgeist',
      ],
      isoMarkers: ['ISO 8601', 'CE', 'BCE', 'AD', 'BC'],
    },
    culture: {
      core: [
        'culture',
        'cultural',
        'heritage',
        'tradition',
        'ritual',
        'symbol',
        'культура',
        'наследие',
        'обычай',
        'Kultur',
        'Erbe',
        'Brauch',
        'culture',
        'patrimoine',
        'cultura',
        'patrimonio',
        'cultura',
        'մշակույթ',
        'cultus',
        'mos',
        'mores',
        'symbolon',
      ],
      nuances: [
        'acculturation',
        'syncretism',
        'folklore',
        'high culture',
        'popular culture',
        'identity',
        'canon',
        'vernacular',
        'anthropology of',
        'ethos',
      ],
      isoMarkers: ['UNESCO', 'ICH', 'WHC'],
    },
    aesthetics: {
      core: [
        'aesthetics',
        'beauty',
        'art',
        'design',
        'form',
        'harmony',
        'эстетика',
        'красота',
        'искусство',
        'Ästhetik',
        'Schönheit',
        'Kunst',
        'esthétique',
        'beau',
        'arte',
        'bellezza',
        'estética',
        'arte',
        'գեղագիտություն',
        'pulchritudo',
        'ars',
        'venustas',
      ],
      nuances: [
        'sublime',
        'kitsch',
        'proportion',
        'golden ratio',
        'gestalt',
        'taste',
        'composition',
        'palette',
        'texture',
        'minimalism',
      ],
      isoMarkers: ['ISO 12647', 'Pantone', 'CIE Lab'],
    },
    technology: {
      core: [
        'technology',
        'technical',
        'digital',
        'system',
        'software',
        'hardware',
        'network',
        'data',
        'технология',
        'цифровой',
        'система',
        'Technologie',
        'digital',
        'System',
        'technologie',
        'numérique',
        'tecnologia',
        'tecnología',
        'sistema',
        'տեխնոլոգիա',
        'technologia',
        'machina',
        'instrumentum',
      ],
      nuances: [
        'scalability',
        'latency',
        'throughput',
        'encryption',
        'virtualization',
        'containerization',
        'DevOps',
        'CI CD',
        'stack',
        'architecture',
      ],
      isoMarkers: ['ISO 27001', 'ISO 20000', 'ITIL', 'IEEE', 'RFC'],
    },
    spirituality: {
      core: [
        'spirit',
        'spiritual',
        'sacred',
        'soul',
        'faith',
        'divine',
        'transcendent',
        'свет',
        'дух',
        'священный',
        'душа',
        'Geist',
        'heilig',
        'Seele',
        'esprit',
        'sacré',
        'spirito',
        'sacro',
        'espíritu',
        'sagrado',
        'հոգևոր',
        'lux',
        'spiritus',
        'sacer',
        'numen',
        'sanctus',
      ],
      nuances: [
        'mysticism',
        'contemplation',
        'grace',
        'revelation',
        'liturgy',
        'icon',
        'pilgrimage',
        'karma',
        'dharma',
        'theosis',
      ],
      isoMarkers: ['ISO 21401', 'GSTC'],
    },
    semantics: {
      core: [
        'meaning',
        'semantics',
        'semantic',
        'sense',
        'signification',
        'denotation',
        'connotation',
        'смысл',
        'семантика',
        'значение',
        'Bedeutung',
        'Sinn',
        'Semantik',
        'sens',
        'sémantique',
        'significado',
        'significato',
        'sentido',
        'իմաստ',
        'imast',
        'sensus',
        'significatio',
        'notio',
        'verbum',
      ],
      nuances: [
        'implicature',
        'presupposition',
        'polysemy',
        'synonymy',
        'antonymy',
        'pragmatics',
        'truth conditions',
        'reference',
        'intension',
        'extension',
      ],
      isoMarkers: ['ISO 704', 'ISO 1087', 'SKOS', 'OWL'],
    },
    context: {
      core: [
        'context',
        'situation',
        'background',
        'frame',
        'setting',
        'environment',
        'контекст',
        'ситуация',
        'фон',
        'Kontext',
        'Hintergrund',
        'Rahmen',
        'contexte',
        'cadre',
        'contesto',
        'sfondo',
        'contexto',
        'marco',
        'համատեքստ',
        'contextus',
        'circumstantia',
        'ambitus',
      ],
      nuances: [
        'indexicality',
        'deixis',
        'discourse',
        'cohesion',
        'coherence',
        'frame semantics',
        'situational',
        'embedding',
        'scope',
        'grounding',
      ],
      isoMarkers: ['ISO 639', 'ISO 15924', 'BCP 47'],
    },
    intent: {
      core: [
        'intent',
        'intention',
        'purpose',
        'goal',
        'will',
        'volition',
        'aim',
        'намерение',
        'цель',
        'замысел',
        'воля',
        'Absicht',
        'Vorsatz',
        'Ziel',
        'intention',
        'but',
        'intenzione',
        'scopo',
        'intención',
        'propósito',
        'մտադրություն',
        'mtadrutyun',
        'voluntas',
        'propositum',
        'finalitas',
      ],
      nuances: [
        'premeditation',
        'forethought',
        'mens rea',
        'teleology',
        'vector of will',
        'предумышленность',
        'resolve',
        'deliberation',
        'commitment',
        'directedness',
      ],
      isoMarkers: ['ISO 9001', 'PDCA', 'SMART', 'OKR', 'KPI'],
    },
    imagery: {
      core: [
        'image',
        'imagery',
        'metaphor',
        'vision',
        'figure',
        'symbol',
        'образ',
        'метафора',
        'видение',
        'Bild',
        'Metapher',
        'image',
        'métaphore',
        'visione',
        'metafora',
        'imagen',
        'visión',
        'պատկեր',
        'imago',
        'visio',
        'figura',
        'allegoria',
      ],
      nuances: [
        'synesthesia',
        'allegory',
        'trope',
        'simile',
        'ekphrasis',
        'pictorial',
        'mental image',
        'schema',
        'iconicity',
        'mimesis',
      ],
      isoMarkers: ['ISO 12651', 'SVG', 'PNG metadata'],
    },
    ethics: {
      core: [
        'ethics',
        'ethical',
        'moral',
        'justice',
        'law',
        'duty',
        'virtue',
        'этика',
        'мораль',
        'справедливость',
        'Ethik',
        'Moral',
        'Gerechtigkeit',
        'éthique',
        'morale',
        'etica',
        'ética',
        'moral',
        'էթիկա',
        'ethika',
        'lex',
        'iustitia',
        'virtus',
      ],
      nuances: [
        'deontology',
        'consequentialism',
        'virtue ethics',
        'care ethics',
        'normativity',
        'accountability',
        'transparency',
        'integrity',
        'compliance',
        'fiduciary',
      ],
      isoMarkers: ['ISO 26000', 'ISO 37001', 'ISO 19600', 'GDPR', 'HIPAA'],
    },
  },
};
